name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ecowitt2mqtt:

    runs-on: ubuntu-latest

    steps:
    - name: Record the Unix epoch
      run: |
        echo "docker_tag=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ${{ github.actor }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Build Ecowitt2MQTT Container
      run: cd ecowitt2mqtt/ && docker build . --file Dockerfile --build-arg=BUILD_FROM=ghcr.io/home-assistant/amd64-base-python:3.9-alpine3.14 --tag ghcr.io/${{ github.actor }}/ecowitt2mqtt:${{ env.docker_tag }}
      
    - name: Push Ecowitt2MQTT Container
      run: docker push ghcr.io/${{ github.actor }}/ecowitt2mqtt:${{ env.docker_tag }}
