name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ecowitt2mqtt:

    runs-on: ubuntu-latest

    steps:
    - name: Record the Unix epoch
      run: |
        echo "docker_tag=$(date +%s)" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    
    - name: GHCR Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ${{ github.actor }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Dockerhub Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      uses: docker/login-action@v1.9.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build AMD64
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ecowitt2mqtt/
        file: ecowitt2mqtt/Dockerfile
        build-args: |
          BUILD_FROM=ghcr.io/home-assistant/amd64-base-python:3.9-alpine3.14
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/amd64-ecowitt2mqtt:${{ env.docker_tag }}
          ${{ secrets.DOCKERHUB_USERNAME }}/amd64-ecowitt2mqtt:${{ env.docker_tag }}

    - name: Build ARMHF
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ecowitt2mqtt/
        file: ecowitt2mqtt/Dockerfile
        build-args: |
          BUILD_FROM=ghcr.io/home-assistant/armhf-base-python:3.9-alpine3.14
        platforms: linux/arm
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/armhf-ecowitt2mqtt:${{ env.docker_tag }}
          ${{ secrets.DOCKERHUB_USERNAME }}/armhf-ecowitt2mqtt:${{ env.docker_tag }}

    - name: Build ARMV7
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ecowitt2mqtt/
        file: ecowitt2mqtt/Dockerfile
        build-args: |
          BUILD_FROM=ghcr.io/home-assistant/armv7-base-python:3.9-alpine3.14
        platforms: linux/armv7
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/armv7-ecowitt2mqtt:${{ env.docker_tag }}
          ${{ secrets.DOCKERHUB_USERNAME }}/armv7-ecowitt2mqtt:${{ env.docker_tag }}

    - name: Build AARCH64
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ecowitt2mqtt/
        file: ecowitt2mqtt/Dockerfile
        build-args: |
          BUILD_FROM=ghcr.io/home-assistant/base-python:3.9-alpine3.14
        platforms: linux/aarch64
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/aarch64-ecowitt2mqtt:aarch64-${{ env.docker_tag }}
          ${{ secrets.DOCKERHUB_USERNAME }}/aarch64-ecowitt2mqtt:aarch64-${{ env.docker_tag }}

    - name: Build i386
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ecowitt2mqtt/
        file: ecowitt2mqtt/Dockerfile
        build-args: |
          BUILD_FROM=ghcr.io/home-assistant/i386-base-python:3.9-alpine3.14
        platforms: linux/i386
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/i386-ecowitt2mqtt:${{ env.docker_tag }}
          ${{ secrets.DOCKERHUB_USERNAME }}/i386-ecowitt2mqtt:${{ env.docker_tag }}
